Repository FC-DEV-FinalProject/FinalProject_2VEN_FE, pull requests merged in 2024-12, with the labels that each got.

#266 [Feat] 전화번호로 이메일 찾기 api 구현 #263
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/hooks/mutations/useEmailFinder.ts
  src/pages/auth/find/EmailFoundPage.tsx
  src/pages/auth/find/FindEmailPage.tsx
  src/utils/validation.ts
Labels: 📬 API, ✨ Feature

#270 [Feat] 로그인 성공 시, 헤더에 프로필 이미지 보여주기 #268
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/api/profile.ts
  src/components/common/Header.tsx
  src/hooks/queries/useFetchPofileImage.ts
  src/hooks/queries/useProfileImage.ts
  src/types/profile.ts
Labels: 📬 API, ✨ Feature

#272 [Feat] 전략 상세 일간분석 예외처리 및 월간분석 조회 API 반영
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/MonthlyAnalysis.tsx
  src/hooks/queries/useFetchMonthlyAnalysis.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/strategyDetail.ts
  src/utils/statistics.ts
Labels: 📬 API

#274 [Feat] 마이페이지 로그아웃 및 자동 로그아웃 구현
  src/components/common/Header.tsx
  src/components/navigation/InvestorMypageNav.tsx
  src/components/navigation/TraderMyPageNav.tsx
  src/hooks/useSesstionTimer.ts
  src/stores/authStore.ts
Labels: ✨ Feature

#275 [Feat] 비밀번호 찾기 페이지 - 이메일 요청/검증 api 구현 및 연결 #273
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/page/signup/SignUpForm.tsx
  src/hooks/mutations/useSignupVerification.ts
  src/hooks/mutations/useVerifacationMutation.tsx
  src/mocks/handlers/auth.handlers.ts
  src/pages/auth/find/FindPasswordPage.tsx
Labels: 📬 API, ✨ Feature

#276 [Feat] 전략승인관리목록 조회, 승인, 거부 api 연동 추가
  src/api/apiEndpoints.ts
  src/api/strategyApproval.ts
  src/components/page/admin/RejectTextarea.tsx
  src/components/page/admin/StrategyStatusLabel.tsx
  src/hooks/mutations/useStrategyApprovalMutations.ts
  src/hooks/queries/useStrategyApprovalList.ts
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
Labels: 📬 API, 🔨 Refactor

#279 [Feat] 비밀번호 재설정 페이지 구현 (+api연결) #269
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/hooks/mutations/useResetPasswordMutation.ts
  src/pages/auth/find/FindPasswordPage.tsx
  src/pages/auth/find/ResetPasswordPage.tsx
Labels: 📬 API, ✨ Feature

#271 [feat] 문의등록 POST API 연결(근데 토스트가 안돼요..)
  src/api/inquiryCreate.ts
  src/components/page/inquiry-create/InquiryCreateForm.tsx
  src/components/page/inquiry-create/inquiry-form-content/InquiryStrategyInfo.tsx
  src/hooks/mutations/useSubmitInquiryCreate.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/inquiryCreate.ts
Labels: 📬 API

#286 [fix] 토스트 z-index 순위 높히기, contentModal의 onAction 수정(브랜치삭제하지마세요. 또 작업해야함)
  src/components/common/ContentModal.tsx
  src/components/common/Toast.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/test-page/ContentModalTestPage.tsx
  src/stores/contentModalStore.ts
Labels: 🐞 BugFix

#287 [Feat] 전략 등록, 수정 페이지 제안서 업로드/삭제 API 연동 및 기능 구현
  src/api/strategy.ts
  src/components/common/Toast.tsx
  src/components/page/strategy/StrategyForm.tsx
  src/components/page/strategy/form-content/FileUpload.tsx
  src/hooks/mutations/useUploadProposalFile.ts
  src/pages/mypage/trader/StrategyEditPage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
  src/pages/strategy/StrategyListPage.tsx
  src/types/strategy.ts
  src/types/strategyDetail.ts
  src/utils/fileHelper.ts
Labels: 📬 API

#288 [feat] 메인페이지 Auth 값에 따라 가입버튼 상태
  src/pages/HomePage.tsx
Labels: ✨ Feature

#290 [Feat] 전략 승인 요청 , 승인 요청 목록 조회 API 연결
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/FileDownSection.tsx
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/hooks/mutations/useDailyAnalysis.ts
  src/hooks/mutations/useStrategyDetailDelete.ts
  src/hooks/mutations/useStrategyDetailMutation.ts
  src/hooks/queries/useFetchApprove.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/utils/statistics.ts
Labels: 📬 API

#291 [Feat] 회원가입 페이지 구현 (+api) #40
  src/api/auth.ts
  src/components/page/signup/SignUpForm.tsx
  src/components/terms/TermsContainer.tsx
  src/constants/auth.ts
  src/hooks/useFormValidation.ts
  src/hooks/useSignupMutation.ts
  src/pages/auth/signup/SignUpPage.tsx
  src/pages/auth/signup/SignUpSuccessPage.tsx
  src/types/auth.ts
Labels: 📬 API, ✨ Feature

#294 [Feat] 테이블모달 수정(곁들어진 유효성체크 수정, 오타 수정)
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/TableModal.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/stores/tableModalStore.ts
  src/utils/statistics.ts
Labels: 🐞 BugFix

#295 [feat] 메인페이지 트레이더,전략 수 조회하기 api 연결
  src/api/apiEndpoints.ts
  src/api/traderStats.ts
  src/components/page/home/TraderStats.tsx
  src/hooks/queries/useFetchStrategyTraderCount.ts
  src/pages/HomePage.tsx
Labels: 📬 API

#298 [Feat] 일간분석 엑셀 업로드 기능 구현
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/IconTagSection.tsx
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/hooks/mutations/useDailyAnalysis.ts
Labels: 📬 API

#296 [Feat] 통합검색결과 페이지 구현(+api) #293
  src/api/apiEndpoints.ts
  src/api/search.ts
  src/components/common/Header.tsx
  src/components/common/TraderList.tsx
  src/components/page/search/SearchInput.tsx
  src/components/page/search/SearchedStrategyList.tsx
  src/constants/routes.ts
  src/hooks/queries/useSearch.ts
  src/pages/search/SearchTotalResultsPage.tsx
  src/pages/trader/TraderListPage.tsx
  src/route/Router.tsx
  src/stores/searchStore.ts
  src/types/search.ts
  src/utils/mappers.ts
Labels: 📬 API, ✨ Feature

#301 [Feat] DatePicker 컴포넌트 추가 (#297)
  package-lock.json
  package.json
  src/components/common/DatePicker.tsx
  src/hooks/useOnClickOutside.ts
  src/pages/HomePage.tsx
  src/pages/test-page/DatepickerTestPage.tsx
  src/utils/calendar.ts
Labels: 🎨 Html&css, ✨ Feature

#299 [Feat] 실계좌 이미지 조회, 등록, 삭제 기능 구현
  src/api/apiEndpoints.ts
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/ImgSection.tsx
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/hooks/mutations/useAccountMutation.ts
  src/hooks/queries/useAccountImg.ts
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 📬 API

#303 [Feat] 폴더 목록 조회, 폴더 등록, 수정, 삭제 API 연동
  src/api/apiEndpoints.ts
  src/api/folders.ts
  src/components/page/mypage-investor/myfolder/FolderList.tsx
  src/components/page/mypage-investor/myfolder/FolderModal.tsx
  src/hooks/mutations/useFollwingStrategyMutation.ts
  src/hooks/queries/useFetchFolderList.ts
  src/pages/HomePage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
Labels: 📬 API

#307 [Fix] 비공개, 미승인 상태인 전략 접근할 수 없도록 리다이렉트 처리
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🐞 BugFix

#305 [Refactor] 투자자쪽 문의 관련 페이지 리팩토링 및 기능 개선
  src/api/inquiries/investor.ts
  src/api/inquiryCreate.ts
  src/api/myInquiry.ts
  src/components/page/inquiry-create/InquiryCreateForm.tsx
  src/components/page/mypage-investor/inquires-detail/Answer.tsx
  src/components/page/mypage-investor/inquires-detail/Question.tsx
  src/components/page/mypage-investor/inquires-edit/InquiresInput.tsx
  src/components/page/mypage-investor/inquires-edit/StrategyInfo.tsx
  src/constants/inquiry.ts
  src/hooks/mutations/useMyInquiry.ts
  src/hooks/mutations/useMyInquiryMutations.ts
  src/hooks/mutations/useSubmitInquiryCreate.ts
  src/hooks/mutations/useSubmitInquiryUpdate.ts
  src/hooks/queries/useFetchInquiryDetail.ts
  src/hooks/useToastWithNavigate.ts
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiresEditPage.tsx
  src/pages/strategy/InquiryPage.tsx
  src/types/inquiries.ts
  src/types/inquiryCreate.ts
  src/types/myinquires.ts
Labels: 🔨 Refactor

#313 [Feat] 관리자이메일로 로그인 시 상단에 로그아웃 버튼 추가 (#292)
  src/components/common/Header.tsx
  src/pages/HomePage.tsx
Labels: ✨ Feature

#316 [Feat] 키워드에 대한 전략/트레이더 상세 페이지 #308
  src/api/apiEndpoints.ts
  src/api/search.ts
  src/hooks/queries/useSearch.ts
  src/pages/search/SearchResultsInStrategy.tsx
  src/pages/search/SearchResultsInTrader.tsx
  src/pages/search/SearchTotalResultsPage.tsx
  src/types/search.ts
  src/utils/string.ts
Labels: 📬 API, 🎨 Html&css, ✨ Feature

#319 [Feat] 전략 상세 차트 컴포넌트 생성, role에 따른 접근 제한 수정
  src/api/strategyDetail.ts
  src/components/common/StrategyChart.tsx
  src/components/page/strategy-detail/FileDownSection.tsx
  src/components/page/strategy-detail/IconTagSection.tsx
  src/components/page/strategy-detail/StrategyIndicator.tsx
  src/components/page/strategy-detail/chart/ChartSection.tsx
  src/constants/strategyAnalysis.ts
  src/hooks/mutations/useDailyAnalysis.ts
  src/hooks/queries/useFetchApprove.ts
  src/hooks/queries/useStrategyChart.ts
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 📬 API, ✨ Feature

#320 [refactor] 전략관리승인목록의 전략상태컴포넌트 추가 및 메뉴 알람 제거
  src/components/navigation/AdminNav.tsx
  src/components/page/admin/StrategyOperationStatus.tsx
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
Labels: 🔨 Refactor

#315 [feat] 메인(홈)페이지 SMSCORE TOP5 조회하기 api 연결 (#54)
  src/api/home/strategyTraderCount.ts
  src/api/home/topStrategyRank.ts
  src/components/page/home/StrategyTraderCount.tsx
  src/components/page/home/TopStrategyList.tsx
  src/hooks/queries/useFetchStrategyTraderCount.ts
  src/hooks/queries/useFetchTopStrategy.ts
  src/pages/HomePage.tsx
Labels: 📬 API

#321 [feat] 상단 헤더의 트레이더메뉴 전체조회 페이지 api 구현
  src/api/search.ts
  src/hooks/queries/useSearch.ts
  src/pages/search/SearchResultsInTrader.tsx
  src/pages/trader/TraderListPage.tsx
Labels: 📬 API

#322 [Refactor] 트레이더 문의하기 CRUD api 연결및 문의관련 기능개선
  src/api/inquiries/investor.ts
  src/api/inquiries/trader.ts
  src/components/page/mypage-trader/TraderAnswer.tsx
  src/components/page/mypage-trader/TraderQuestion.tsx
  src/components/page/mypage/inquires-detail/InquiryQuestion.tsx
  src/components/page/mypage/inquires-detail/InvestorAnswer.tsx
  src/components/page/mypage/inquires-detail/TraderAnswerEditor.tsx
  src/components/page/mypage/inquires-detail/TraderAnswerViewer.tsx
  src/components/page/mypage/inquires-edit/InquiresInput.tsx
  src/components/page/mypage/inquires-edit/StrategyInfo.tsx
  src/hooks/mutations/useMyInquiryMutations.ts
  src/hooks/mutations/useTraderReplyMutations.ts
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiresEditPage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/InquiryDetailPage.tsx
  src/pages/strategy/InquiryPage.tsx
  src/types/inquiries.ts
Labels: 📬 API, 🔨 Refactor

#330 [feat] 파비콘 추가 및 풋터 주소변경
  index.html
  src/assets/images/favicon/android-chrome-192x192.png
  src/assets/images/favicon/android-chrome-512x512.png
  src/assets/images/favicon/apple-touch-icon.png
  src/assets/images/favicon/favicon-16x16.png
  src/assets/images/favicon/favicon-32x32.png
  src/assets/images/favicon/favicon.ico
  src/assets/images/favicon/favicon.png
  src/assets/images/favicon/favicon.svg
  src/assets/images/favicon/safari-pinned-tab.svg
  src/assets/images/manifest.json
  src/components/common/Footer.tsx
Labels: 🎨 Html&css, ✨ Feature

#331 [Feat] 트레이더 나의 전략 조회 기능 구현 및 스타일/문구 수정
  src/api/apiEndpoints.ts
  src/api/traderStrategies.ts
  src/hooks/queries/useFetchTraderStrategies.ts
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/TraderMyPage.tsx
  src/pages/mypage/trader/TraderProfilePage.tsx
  src/utils/roleUtils.ts
Labels: 📬 API, 🎨 Html&css

#332 [Feat] 전략 팔로우/언팔로우 API 연동
  src/api/apiEndpoints.ts
  src/api/follow.ts
  src/components/common/StrategyList.tsx
  src/components/page/mypage-investor/myfolder/FollowModal.tsx
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/hooks/queries/useFetchFolderList.ts
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 📬 API

#341 [Feat] 전략상세검색 필터 컴포넌트 구현 #317 (머지가능/ 브랜치는 삭제하지 말아주세요)
  src/api/search.ts
  src/components/common/DatePicker.tsx
  src/components/page/search/SearchedStrategyList.tsx
  src/components/page/search/StrategyDetailFilter.tsx
  src/constants/createOptions.ts
  src/constants/filterOptions.ts
  src/constants/iconUrls.ts
  src/hooks/queries/useSearch.ts
  src/pages/search/SearchResultsInStrategy.tsx
  src/pages/test-page/DatepickerTestPage.tsx
  src/types/search.ts
  src/utils/calendar.ts
  src/utils/mappers.ts
Labels: 📬 API, ✨ Feature

#340 [feat] 메인페이지 SMScore Top5 api명세서 따로 만들어주셔서 재api 연결 (#325)
  src/api/apiEndpoints.ts
  src/api/home/topStrategyRank.ts
  src/components/page/home/TopStrategyList.tsx
Labels: 📬 API

#342 [Design] 트레이더 프로필 조회 페이지 CSS
  src/components/navigation/TraderPageNav.tsx
  src/layouts/TraderPageLayout.tsx
  src/pages/trader/TraderDetailPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#344 [Feat] 관심 전략 내부 폴더 이동 API 연동
  src/api/follow.ts
  src/components/page/mypage-investor/myfolder/FolderModal.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/strategy/StrategyListPage.tsx
Labels: 📬 API

#343 [Fix] 전략 상세 페이지 통계탭 단위 처리 및 비회원 블러 처리
  src/api/stockType.ts
  src/api/strategyDetail.ts
  src/api/tradingType.ts
  src/components/common/LineChart.tsx
  src/components/common/StrategyChart.tsx
  src/components/page/strategy-detail/ReasonItem.tsx
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/MonthlyAnalysis.tsx
  src/hooks/mutations/useDailyAnalysis.ts
  src/hooks/mutations/useStrategyDetailMutation.ts
  src/hooks/queries/useFetchDailyAnalysis.ts
  src/hooks/queries/useFetchMonthlyAnalysis.ts
  src/hooks/queries/useFetchStrategyDetail.ts
  src/hooks/queries/useStatistics.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/admin.ts
  src/utils/statistics.ts
Labels: 🐞 BugFix, ✨ Feature

#347 [Feat] 트레이더 프로필 조회 API 연동 및 CSS 수정
  src/api/traderStrategies.ts
  src/components/navigation/TraderProfilePageNav.tsx
  src/components/page/mypage/ProfileSection.tsx
  src/hooks/queries/useFetchTraderStrategies.ts
  src/layouts/TraderProfilePageLayout.tsx
  src/pages/trader/TraderDetailPage.tsx
  src/route/Router.tsx
Labels: 📬 API

#351 [Fix] 토스트 수정
  src/components/common/Toast.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiresEditPage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/strategy/InquiryPage.tsx
Labels: 🐞 BugFix

#352 [Fix] 매매유형, 상품유형 관리 다중삭제 적용
  src/api/stockType.ts
  src/api/tradingType.ts
  src/components/page/strategy-detail/IconTagSection.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/hooks/mutations/useStockType.ts
  src/hooks/mutations/useTradingType.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
Labels: 🐞 BugFix

#354 [Feat] 나의 관심 전략 폴더 목록 페이지네이션 추가
  src/api/folders.ts
  src/components/page/mypage-investor/myfolder/FolderModal.tsx
  src/components/page/mypage-investor/myfolder/FollowModal.tsx
  src/hooks/queries/useFetchFolderList.ts
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
Labels: ✨ Feature

#358 [Fix] 상세 페이지 이동시 Nav active 풀리는 이슈 해결
  src/components/common/NavigationMenu.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
Labels: 🐞 BugFix

#356 [feat] 회원정보 수정 기능 구현중 (#312)
  src/api/apiEndpoints.ts
  src/api/profile.ts
  src/components/page/mypage/ProfileManager.tsx
  src/hooks/mutations/useUpdatePersonalDetails.ts
  src/hooks/queries/useFetchPersonalDetails.ts
  src/types/profile.ts
Labels: ✨ Feature

#360 [Feat] 실계좌 이미지 클릭 시 상세 확인할 수 있도록 모달 처리
  src/components/page/mypage-investor/myfolder/FolderModal.tsx
  src/components/page/strategy-detail/ImgSection.tsx
Labels: 🎨 Html&css

#361 [Feat] 프로필 관리 - 비밀번호 재설정
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/api/profile.ts
  src/components/page/mypage/PasswordChange.tsx
  src/hooks/mutations/useChangePassword.ts
  src/types/profile.ts
Labels: 📬 API

#363 [Feat] 상세검색 필터, 입력창 입력한 값도 상세검색 api 호출하도록 구현
  src/api/search.ts
  src/components/common/DatePicker.tsx
  src/components/page/search/SearchedStrategyList.tsx
  src/components/page/search/StrategyDetailFilter.tsx
  src/hooks/queries/useSearch.ts
  src/pages/auth/SignInPage.tsx
  src/pages/search/SearchResultsInStrategy.tsx
  src/pages/search/SearchResultsInTrader.tsx
  src/pages/test-page/DatepickerTestPage.tsx
Labels: 📬 API, ✨ Feature

#362 [feat] 리뷰(전략상세하단) api 연결
  src/api/apiEndpoints.ts
  src/api/review.ts
  src/components/page/strategy-detail/review/ReviewInputList.tsx
  src/components/page/strategy-detail/review/ReviewItem.tsx
  src/components/page/strategy-detail/review/ReviewSection.tsx
  src/hooks/mutations/useReviewMutation.ts
  src/hooks/queries/useFetchReview.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/review.ts
Labels: 📬 API

#366 [Feat] 프로필 이미지 업로드, 삭제 기능 구현
  src/api/apiEndpoints.ts
  src/api/profile.ts
  src/components/navigation/InvestorMypageNav.tsx
  src/components/navigation/TraderMyPageNav.tsx
  src/components/page/mypage/ProfileManager.tsx
  src/components/page/mypage/ProfileSection.tsx
  src/hooks/mutations/useProfileImageMutations.ts
  src/types/profile.ts
Labels: 📬 API

#369 [Fix] 비로그인시 문의하기, 전략 팔로우 토스트 처리 수정
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/strategy/InquiryPage.tsx
Labels: 🐞 BugFix

#370 [Fix] 비로그인 블러 처리 제거, 리뷰 제한
  src/components/page/strategy-detail/review/ReviewInputList.tsx
  src/components/page/strategy-detail/review/ReviewSection.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🐞 BugFix

#372 [Feat] GlobalNav 메뉴 활성화 상태에 따라 bold 스타일 적용
  src/components/navigation/GlobalNav.tsx
Labels: ✨ Feature

#373 feat: 체크박스 클릭 시 스타일링 변경 (#365)
  src/components/page/search/StrategyDetailFilter.tsx
Labels: 🎨 Html&css

#374 [feat] 회원 탈퇴기능 구현
  src/api/apiEndpoints.ts
  src/api/profile.ts
  src/hooks/mutations/useWithdrawMember.ts
  src/pages/auth/WithdrawalSuccessPage.tsx
  src/pages/mypage/investor/InvestorProfilePage.tsx
  src/pages/mypage/trader/TraderProfilePage.tsx
Labels: 📬 API

#379 [fix] 전략 상세 승인요청 가능 여부 상태 반영
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🐞 BugFix

#378 [feat] OG Tag 추가
  index.html
  src/assets/images/og/og.png
  src/assets/images/og/og.svg
Labels: ✨ Feature

#382 [Fix] 나의 관심전략 페이지 기본폴더 수정 불가 로직 추가
  src/pages/mypage/investor/InvestorMyPage.tsx
Labels: 🐞 BugFix

#384 feat: 역할 및 인증 상태에 따른 라우팅 처리
  src/route/Router.tsx
Labels: ✨ Feature

#386 [Fix] 파비콘, OG Tag 경로 수정
  index.html
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/favicon.png
  public/favicon/favicon.svg
  public/favicon/safari-pinned-tab.svg
  public/og/og.png
  public/og/og.svg
Labels: 🐞 BugFix

#388 [Fix] 레이아웃 수정
  src/layouts/AdminLayout.tsx
  src/layouts/InvestorMypageLayout.tsx
  src/layouts/TraderMyPageLayout.tsx
  src/layouts/TraderProfilePageLayout.tsx
  src/pages/trader/TraderDetailPage.tsx
Labels: 🐞 BugFix

#391 [fix] profileInput 추가 및 회원정보 유효성 체크 (#357)
  src/components/page/mypage/PasswordChange.tsx
  src/components/page/mypage/ProfileInput.tsx
  src/components/page/mypage/ProfileManager.tsx
  src/hooks/queries/useSidebarProfile.ts
Labels: 🐞 BugFix

#392 [fix] 아바타 컴포넌트 적용
  src/components/common/TraderList.tsx
  src/components/navigation/TraderProfilePageNav.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/pages/trader/TraderDetailPage.tsx
Labels: 🐞 BugFix

#394 [Fix] 트레이더 프로필 조회 라우팅 수정
  src/route/Router.tsx
Labels: 🐞 BugFix

#387 [feat] 컴포넌트 스크롤탑 CSS, 리뷰토탈카운트 수정
  src/components/common/ScrollToTop.tsx
  src/components/page/strategy-detail/review/ReviewSection.tsx
  src/pages/HomePage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
  src/pages/strategy/StrategyListPage.tsx
Labels: 🎨 Html&css, ✨ Feature
