Repository FC-DEV-FinalProject/FinalProject_2VEN_FE, pull requests merged in 2024-11, with the labels that each got.

#13 [Setting] 글로벌스타일 세팅
  src/assets/fonts/woff/Pretendard-Bold.woff
  src/assets/fonts/woff/Pretendard-Medium.woff
  src/assets/fonts/woff/Pretendard-Regular.woff
  src/assets/fonts/woff/Pretendard-SemiBold.woff
  src/main.tsx
  src/styles/GlobalStyle.tsx
  src/styles/emotion.d.ts
  src/styles/fonts.d.ts
  src/styles/globalFonts.ts
  src/styles/theme.ts
  src/types/global.d.ts
  src/utils/color.ts
Labels: ⚙ Setting, ✨ Feature

#18 [Feat] 라우터 생성 및 페이지 연결
  .eslintrc.cjs
  src/App.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/navigation/AdminNav.tsx
  src/components/navigation/GlobalNav.tsx
  src/components/navigation/MyPageNav.tsx
  src/constants/routes.ts
  src/layouts/AdminLayout.tsx
  src/layouts/MyPageLayout.tsx
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/pages/Auth/LogInPage.tsx
  src/pages/HomePage.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/auth/WithdrawalSuccessPage.tsx
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/pages/auth/find/EmailFoundPage.tsx
  src/pages/auth/find/FindEmailPage.tsx
  src/pages/auth/find/FindPasswordPage.tsx
  src/pages/auth/find/PasswordResetSuccessPage.tsx
  src/pages/auth/find/ResetPasswordPage.tsx
  src/pages/auth/signup/SignUpFormPage.tsx
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/pages/auth/signup/SignUpSuccessPage.tsx
  src/pages/error/NotFoundPage.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/mypage/investor/InvestorProfilePage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/StrategyCreatePage.tsx
  src/pages/mypage/trader/StrategyEditPage.tsx
  src/pages/mypage/trader/TraderMyPage.tsx
  src/pages/mypage/trader/TraderProfilePage.tsx
  src/pages/search/SearchResultsInStrategy.tsx
  src/pages/search/SearchResultsInTrader.tsx
  src/pages/search/SearchTotalResultsPage.tsx
  src/pages/strategy/InquiryPage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
  src/pages/strategy/StrategyListPage.tsx
  src/pages/trader/TraderDetailPage.tsx
  src/pages/trader/TraderListPage.tsx
  src/route/Router.tsx
  src/types/route.ts
Labels: ✨ Feature

#19 [Feat] RootLayout 컴포넌트 구현
  public/logo.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/navigation/GlobalNav.tsx
  src/layouts/RootLayout.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#21 [Feat] input 컴포넌트 생성
  package-lock.json
  package.json
  src/components/common/Input.tsx
  src/pages/HomePage.tsx
  src/pages/test-page/InputTestPage.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ✨ Feature

#25 [Feat] Modal 컴포넌트 구현
  index.html
  src/components/common/Modal.tsx
  src/pages/test-page/ModalTestPage.tsx
  src/stores/modalStore.ts
Labels: ✨ Feature

#26 [Feat] Button 컴포넌트 생성
  src/components/common/Button.tsx
  src/pages/HomePage.tsx
  src/pages/test-page/ButtonTestPage.tsx
  src/styles/theme.ts
Labels: ✨ Feature

#31 [Feat] Checkbox 컴포넌트 추가 (#28)
  src/components/common/Checkbox.tsx
  src/components/common/CheckboxGroup.tsx
  src/pages/HomePage.tsx
  src/pages/test-page/CheckboxTestPage.tsx
Labels: ✨ Feature

#32 [Feat] Select 컴포넌트 구현
  src/components/common/Select.tsx
  src/pages/test-page/SelectTestPage.tsx
Labels: ✨ Feature

#30 [feat] 토스트 컴포넌트 기능 구현 (#22)
  src/components/common/Toast.tsx
  src/pages/HomePage.tsx
  src/pages/test-page/ToastTestPage.tsx
  src/stores/toastStore.ts
Labels: ✨ Feature

#63 [fix] layout의 main 너비값 빼기
  src/layouts/RootLayout.tsx
Labels: 🐞 BugFix

#61 [Feat] PageHeader 컴포넌트 구현
  src/components/common/PageHeader.tsx
Labels: ✨ Feature

#65 [Fix] Modal 컴포넌트 css 수정
  src/components/common/Modal.tsx
  src/pages/test-page/ModalTestPage.tsx
Labels: 🐞 BugFix

#66 [Feat] 회원가입 카드 선택 페이지 구현 (#16)
  src/assets/images/investor_card.png
  src/assets/images/trader_card.png
  src/components/page/SignupTypeCard.tsx
  src/constants/signup.ts
  src/layouts/RootLayout.tsx
  src/pages/HomePage.tsx
  src/pages/auth/signup/SignUpFormPage.tsx
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/types/signup.ts
Labels: ✨ Feature

#67 [Design] SignUpPage 페이지 생성 (#33)
  src/components/common/Input.tsx
  src/components/page/signup/SignUpForm.tsx
  src/components/terms/TermsContainer.tsx
  src/components/terms/contents/InvestorTerms.tsx
  src/components/terms/contents/PrivacyTerms.tsx
  src/components/terms/contents/TraderTerms.tsx
  src/components/terms/contents/index.ts
  src/components/terms/index.ts
  src/constants/signup.ts
  src/pages/auth/signup/SignUpFormPage.tsx
  src/pages/auth/signup/SignUpPage.tsx
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/route/Router.tsx
  src/styles/GlobalStyle.tsx
  src/types/signup.ts
Labels: 🎨 Html&css, ✨ Feature

#69 [Design] 전략 상세 페이지 제목, 내용, 지표 영역 퍼블리싱
  src/components/page/strategy/StrategyContent.tsx
  src/components/page/strategy/StrategyIndicator.tsx
  src/components/page/strategy/StrategyTitleSection.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🎨 Html&css

#70 [Feat] 검색 입력 및 마이페이지 링크 추가 (#20)
  src/components/common/Header.tsx
  src/components/page/search/SearchInput.tsx
Labels: ✨ Feature

#73 [Design] 회원가입 성공 페이지 퍼블리싱/스타일링 (#34)
  src/assets/images/signup_success.png
  src/constants/signup.ts
  src/pages/HomePage.tsx
  src/pages/auth/signup/SignUpSuccessPage.tsx
Labels: 🎨 Html&css

#75 [Design] 전략 상세 탭 메뉴 구현
  src/components/page/strategy/StrategyTab.tsx
  src/components/page/strategy/tabmenu/AccountVerify.tsx
  src/components/page/strategy/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy/tabmenu/MonthlyAnalysis.tsx
  src/components/page/strategy/tabmenu/Statistics.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🎨 Html&css

#82 [Feat] 전략등록 css, 파일업로드 기능 구현
  src/components/common/Select.tsx
  src/components/page/strategy-create/StrategyCreateForm.tsx
  src/components/page/strategy-create/form-content/FileUpload.tsx
  src/components/page/strategy-create/form-content/ProductType.tsx
  src/components/page/strategy-create/form-content/StrategyIntro.tsx
  src/components/page/strategy-create/form-content/StrategyName.tsx
  src/hooks/useCreateFormValidation.ts
  src/pages/mypage/trader/StrategyCreatePage.tsx
  src/utils/fileHelper.ts
Labels: 🎨 Html&css, ✨ Feature

#89 [Design] 메인페이지 투자자섹션 CSS 스타일 구현
  src/assets/images/ani_trader.png
  src/assets/images/apt_trader.png
  src/assets/images/investor_main.png
  src/assets/images/nimo_trader.png
  src/pages/HomePage.tsx
Labels: 🎨 Html&css

#98 [Feat] 전략 목록 컴포넌트 구현
  src/assets/images/analytics_graph.png
  src/assets/images/producttype_futures.png
  src/assets/images/producttype_stock.png
  src/assets/images/tradetype_H.png
  src/assets/images/tradetype_P.png
  src/components/common/StrategyList.tsx
  src/pages/test-page/StrategyListTestPage.tsx
Labels: ✨ Feature

#95 [Design] 전략 상세 통계 테이블 퍼블리싱
  src/components/page/strategy-detail/StrategyContent.tsx
  src/components/page/strategy-detail/StrategyIndicator.tsx
  src/components/page/strategy-detail/StrategyTab.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/MonthlyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/StatisticsTable.tsx
  src/components/page/strategy/tabmenu/Statistics.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🎨 Html&css

#99 [Design] 전략상세 실계좌 이미지 컴포넌트 구현
  src/components/page/strategy-detail/ImgSection.tsx
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/utils/fileHelper.ts
Labels: 🎨 Html&css

#100 [Design] 이메일찾기 페이지 생성
  src/assets/images/ani_trader.png
  src/assets/images/investor_main.png
  src/assets/images/nimo_trader.png
  src/components/common/Input.tsx
  src/constants/routes.ts
  src/pages/auth/SignInPage.tsx
  src/pages/auth/find/FindEmailPage.tsx
  src/pages/auth/signup/SignUpSuccessPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#102 [Design] 비밀번호 찾기 페이지 생성
  public/_redirects
  public/mockServiceWorker.js
  src/assets/images/tick.svg
  src/pages/auth/find/FindPasswordPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#109 [Design] 비밀번호 변경 완료 페이지 생성
  src/assets/images/resetpass_success.png
  src/pages/auth/find/PasswordResetSuccessPage.tsx
  src/pages/auth/signup/SignUpSuccessPage.tsx
Labels: 🎨 Html&css

#110 [Design]관리자 상품유형 관리 페이지 퍼블리싱
  src/components/navigation/AdminNav.tsx
  src/components/page/admin/TypeTable.tsx
  src/layouts/AdminLayout.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#113 [Design] 이용약관 페이지 구현 (#68)
  src/components/terms/contents/InvestorTerms.tsx
  src/components/terms/contents/PrivacyTerms.tsx
  src/components/terms/contents/TraderTerms.tsx
  src/components/terms/style.ts
Labels: 🎨 Html&css

#112 [Design] 전략 목록(랭킹) css
  src/components/common/PageHeader.tsx
  src/components/common/Select.tsx
  src/components/common/StrategyList.tsx
  src/pages/mypage/trader/StrategyCreatePage.tsx
  src/pages/strategy/StrategyListPage.tsx
  src/pages/test-page/StrategyListTestPage.tsx
Labels: 🎨 Html&css

#115 [Feat] verification input 구현
  src/components/page/signup/SignupTypeCard.tsx
  src/components/page/signup/VerificationInput.tsx
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/utils/time.ts
  src/utils/validation.ts
Labels: ✨ Feature

#116 [Feat] 관리자 인증 페이지 UI 기능 구현 (#106)
  src/components/page/signup/VerificationInput.tsx
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/route/Router.tsx
Labels: ✨ Feature

#118 [Design] 전략 상세페이지 퍼블리싱
  src/components/page/strategy-detail/FileDownSection.tsx
  src/components/page/strategy-detail/StrategyIndicator.tsx
  src/components/page/strategy-detail/StrategyTab.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/components/page/strategy-detail/section/ChartSection.tsx
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/table/TableModal.tsx
  src/components/page/strategy-detail/tabmenu/AccountVerify.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/MonthlyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/StatisticsTable.tsx
  src/pages/strategy/StrategyDetailPage.tsx
  src/stores/tableModalStore.ts
Labels: 🎨 Html&css

#117 [Design] 메인페이지 트레이더섹션 CSS 스타일 구현
  src/assets/images/trader_main.png
  src/pages/HomePage.tsx
Labels: 🎨 Html&css

#124 [Refactor] border의 none, !important 빼기
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Pagination.tsx
  src/components/page/signup/VerificationInput.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/components/page/strategy-detail/tabmenu/StatisticsTable.tsx
  src/components/terms/style.ts
  src/pages/mypage/trader/TraderMyPage.tsx
Labels: 🔨 Refactor

#125 [Refactor] 깃허브액션 네트리파이 삭제, 네트리파이 CLI 설치
  .github/workflows/preview-deploy.yml
  .github/workflows/production-deploy.yml
  .github/workflows/sourcery.yml
  .gitignore
  package-lock.json
  package.json
Labels: 🔨 Refactor

#132 [design]매매유형 관리 페이지 퍼블리싱 (#107)
  src/components/page/admin/TypeTable.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
Labels: 🎨 Html&css

#137 [Feat] ContentModal 컴포넌트(공통)
  src/components/common/ContentModal.tsx
  src/components/common/Modal.tsx
  src/pages/test-page/ContentModalTestPage.tsx
  src/stores/contentModalStore.ts
Labels: ✨ Feature

#133 [design] 대표전략통합평균지표이미지 퍼블리싱 (#47)
  package-lock.json
  src/assets/images/everage_metrics_chart.png
  src/pages/HomePage.tsx
Labels: 🎨 Html&css

#139 [Design] 관리자 상품유형, 매매유형 페이지 등록 모달 구현
  src/components/common/ContentModal.tsx
  src/components/page/admin/FileInput.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/test-page/ContentModalTestPage.tsx
  src/stores/contentModalStore.ts
Labels: 🎨 Html&css

#140 [Feat] 비밀번호 찾기 UI 기능 구현 (#128)
  src/components/page/signup/VerificationInput.tsx
  src/pages/auth/find/FindPasswordPage.tsx
  src/utils/validation.ts
Labels: ✨ Feature

#142 [Fix] 페이지 렌더링 시에만 카운트 다운이 따닥으로 감소하는 문제 해결
  src/components/page/signup/VerificationInput.tsx
  src/pages/auth/SignInPage.tsx
  src/pages/auth/admin/AdminVerifyPage.tsx
Labels: 🐞 BugFix

#144 [Setting, Refactor] API와 MSW production 세팅
  public/mockServiceWorker.js
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/main.tsx
  src/mocks/handlers/example.handlers.ts
  src/mocks/handlers/index.ts
  src/mocks/mockEndpoints.ts
  src/pages/mypage/trader/TraderMyPage.tsx
  src/pages/test-page/APITestPage.tsx
  src/pages/test-page/MockTestPage.tsx
Labels: ⚙ Setting, 🔨 Refactor

#154 [Design] 투자자 마이페이지 - 나의 문의 CSS
  src/components/navigation/InvestorMypageNav.tsx
  src/constants/routes.ts
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#156 [Refactor] api/auth.ts에서 리액트쿼리 분리 (#155)
  src/api/auth.ts
  src/hooks/mutations/useAuthMutation.ts
  src/pages/HomePage.tsx
  src/pages/auth/SignInPage.tsx
Labels: 🔨 Refactor

#157 [Design] 전략 수정 페이지 CSS
  src/pages/mypage/trader/StrategyEditPage.tsx
Labels: 🎨 Html&css

#160 [Feat] 전략 상세페이지 기본 정보 MSW 적용
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/StrategyContent.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/hooks/useFetchStrategyDetail.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/strategyDetail.handlers.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/utils/dateFormat.ts
Labels: 📬 API

#164 feat: 트레이더 마이페이지 전략관리 레이아웃 및 라우팅 추가 (#111)
  src/components/navigation/MyPageNav.tsx
  src/components/navigation/TraderMyPageNav.tsx
  src/layouts/MyPageLayout.tsx
  src/layouts/TraderMyPageLayout.tsx
  src/pages/mypage/trader/TraderMyPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#161 [Feat] 관리자 매매유형 관리 페이지 API 적용
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/api/stockType.ts
  src/api/tradingType.ts
  src/components/page/admin/FileInput.tsx
  src/components/page/admin/TypeTable.tsx
  src/hooks/useTradingType.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/test-page/APITestPage.tsx
  src/types/admin.ts
Labels: 📬 API, 🆘 Help wanted

#163 [Refactor] SignInPage (#162)
  src/components/common/Input.tsx
  src/constants/auth.ts
  src/hooks/mutations/useAuthMutation.ts
  src/pages/auth/SignInPage.tsx
  src/utils/validation.ts
Labels: 🐞 BugFix, 🔨 Refactor

#170 [Feat] 상품유형(투자자산분류) 관리 페이지 백엔드 API 적용
  src/api/apiEndpoints.ts
  src/api/stockType.ts
  src/api/strategyDetail.ts
  src/components/page/admin/FileInput.tsx
  src/components/page/admin/TypeTable.tsx
  src/hooks/mutations/useStockType.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/types/admin.ts
Labels: 📬 API

#171 [Feat] 전화번호로 이메일찾기 페이지 구현 (#148)
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/constants/auth.ts
  src/hooks/mutations/useEmailFinder.ts
  src/mocks/handlers/auth.handlers.ts
  src/mocks/handlers/index.ts
  src/pages/auth/find/EmailFoundPage.tsx
  src/pages/auth/find/FindEmailPage.tsx
  src/utils/validation.ts
Labels: 📬 API, ✨ Feature

#172 [Feat] 닉네임 중복검사 기능 구현 (msw)
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/page/signup/SignUpForm.tsx
  src/constants/auth.ts
  src/hooks/mutations/useNicknameCheck.ts
  src/mocks/handlers/auth.handlers.ts
  src/mocks/handlers/index.ts
  src/utils/validation.ts
Labels: 📬 API, ✨ Feature

#175 [feat] 트레이더 목록 페이지 추가수정 건
  src/components/common/TraderList.tsx
  src/pages/trader/TraderListPage.tsx
Labels: ✨ Feature

#178 [Design] 라인 차트 컴포넌트 생성
  src/components/common/LineChart.tsx
Labels: 🎨 Html&css

#179 [Design] 투자자 마이페이지 - 문의하기 상세 CSS
  src/components/page/mypage-investor/inquires-detail/Answer.tsx
  src/components/page/mypage-investor/inquires-detail/Question.tsx
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/types/myinquiresDetail.ts
Labels: 🎨 Html&css

#181 [feat] 문의등록 페이지 CSS (#177)
  src/components/page/inquiry-create/InquiryCreateForm.tsx
  src/components/page/inquiry-create/inquiry-form-content/InquiryContent.tsx
  src/components/page/inquiry-create/inquiry-form-content/InquiryStrategyInfo.tsx
  src/components/page/inquiry-create/inquiry-form-content/InquiryTitle.tsx
  src/pages/strategy/InquiryPage.tsx
Labels: 🎨 Html&css, ✨ Feature

#183 fix: 닉네임 중복 검사 로직 수정 (#182)
  src/constants/auth.ts
  src/utils/validation.ts
Labels: 🐞 BugFix

#186 [Feat] 로그인 실제 api 연동 ( #147)
  src/api/apiClient.ts
  src/api/auth.ts
  src/components/terms/TermsContainer.tsx
  src/hooks/mutations/useAuthMutation.ts
  src/pages/auth/SignInPage.tsx
  src/types/auth.ts
  src/types/route.ts
  src/utils/auth.ts
  vite.config.ts
Labels: 📬 API

#187 [Design] 마이페이지 투자자, 트레이더, 관리자 판형 통일화
  src/components/common/Button.tsx
  src/components/common/NavMenuItem.tsx
  src/components/common/NavigationMenu.tsx
  src/components/navigation/AdminNav.tsx
  src/components/navigation/InvestorMypageNav.tsx
  src/components/navigation/TraderMyPageNav.tsx
  src/components/page/admin/TypeTable.tsx
  src/components/page/mypage/ProfileSection.tsx
  src/layouts/AdminLayout.tsx
  src/layouts/InvestorMypageLayout.tsx
  src/layouts/TraderMyPageLayout.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/mypage/investor/InvestorProfilePage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/TraderMyPage.tsx
  src/pages/mypage/trader/TraderProfilePage.tsx
Labels: 🎨 Html&css

#188 [Feat] 전략 상세 기본 정보 조회 API 반영
  src/api/strategyDetail.ts
  src/api/tradingType.ts
  src/components/page/strategy-detail/IconTagSection.tsx
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/components/page/strategy-detail/StrategyTitleSection.tsx
  src/hooks/mutations/useStrategyDetailDelete.ts
  src/hooks/queries/useFetchStrategyDetail.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/strategyDetail.ts
Labels: 📬 API

#190 [Design] 통합검색 결과페이지 퍼블리싱/CSS (#180)
  src/assets/images/default_avatar.png
  src/components/common/PageHeader.tsx
  src/components/page/search/SearchedStrategyList.tsx
  src/constants/routes.ts
  src/pages/search/SearchTotalResultsPage.tsx
  src/route/Router.tsx
Labels: 🎨 Html&css

#192 [Design] 관리자페이지, 투자자/트레이더 마이페이지 레이아웃 스타일링 재조정
  src/layouts/AdminLayout.tsx
  src/layouts/InvestorMypageLayout.tsx
  src/layouts/TraderMyPageLayout.tsx
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
  src/pages/mypage/investor/InvestorProfilePage.tsx
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/TraderMyPage.tsx
  src/pages/mypage/trader/TraderProfilePage.tsx
Labels: 🎨 Html&css

#191 [Fix] 회원유형선택 페이지에서 회원가입 폼으로 이동 시, role이 제대로 전달되지 않는 문제 수정 (#174)
  src/constants/signup.ts
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/types/signup.ts
  src/utils/auth.ts
Labels: 🐞 BugFix

#193 [Fix] PageHeader 컴포넌트 수정
  src/components/common/PageHeader.tsx
  src/pages/mypage/trader/StrategyCreatePage.tsx
  src/pages/mypage/trader/StrategyEditPage.tsx
  src/pages/strategy/InquiryPage.tsx
  src/pages/strategy/StrategyListPage.tsx
  src/pages/trader/TraderListPage.tsx
Labels: ✨ Feature

#198 [Design] 전략 승인 관리 스타일링(추후 MSW 연결, api 연결)
  src/components/page/admin/RejectTextarea.tsx
  src/components/page/admin/strategyStatusLabel.tsx
  src/pages/admin/strategy/StrategyApprovalListPage.tsx
  src/utils/statusUtils.ts
Labels: 🎨 Html&css

#203 [Feat] 전략 상세 일간분석, 월간분석 조회 msw 적용
  src/api/apiClient.ts
  src/api/strategyDetail.ts
  src/api/tradingType.ts
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/table/TableModal.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/MonthlyAnalysis.tsx
  src/constants/strategyAnalysis.ts
  src/hooks/usePagination.ts
  src/mocks/handlers/dailyAnalysis.handlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/monthlyAnalysis.handlers.ts
  src/pages/strategy/StrategyDetailPage.tsx
Labels: ✨ Feature

#205 [feat] 리뷰(전략상세하단) CSS 스타일링
  src/components/page/strategy-detail/review/ReviewInputList.tsx
  src/components/page/strategy-detail/review/ReviewItem.tsx
  src/components/page/strategy-detail/review/ReviewSection.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🎨 Html&css

#204 [Feat] 역할에 따른 헤더, 네비게이션 처리
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/common/Avatar.tsx
  src/components/common/Header.tsx
  src/components/navigation/GlobalNav.tsx
  src/components/page/search/SearchInput.tsx
  src/components/page/signup/AdminSessionTimer.tsx
  src/components/terms/TermsContainer.tsx
  src/hooks/mutations/useAdminVerifyMutation.ts
  src/hooks/mutations/useAuthMutation.ts
  src/hooks/mutations/useVerifacationMutation.tsx
  src/mocks/handlers/auth.handlers.ts
  src/mocks/handlers/index.ts
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/stores/adminAuthStore.ts
  src/types/auth.ts
  src/types/route.ts
Labels: 📬 API, ✨ Feature

#210 [Feat] 로그인 성공 시 헤더 프로필이미지 가져오기 (#209)
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/common/Header.tsx
  src/hooks/queries/useFetchPofileImage.ts
  src/mocks/handlers/auth.handlers.ts
  src/types/auth.ts
Labels: 📬 API, ✨ Feature

#211 [Design] 투자자 마이페이지 나의 관심전략 CSS
  src/components/common/StrategyList.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
Labels: 🎨 Html&css

#215 [Refactor] responsive input 개선 #214
  src/components/common/Input.tsx
  src/pages/auth/signup/SignUpSelectTypePage.tsx
  src/utils/auth.ts
Labels: 🔨 Refactor

#216 [Fix] StrategyList 컴포넌트 수정
  src/components/common/DropdownMenu.tsx
  src/components/common/StrategyList.tsx
  src/hooks/useDropdown.ts
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/types/strategy.ts
Labels: 🐞 BugFix

#220 [Design] 전략 승인거부 사유 확인 컴포넌트 생성
  src/components/page/strategy-detail/ReasonItem.tsx
  src/components/page/strategy-detail/chart/ChartSection.tsx
  src/components/page/strategy-detail/review/ReviewSection.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 🎨 Html&css

#224 feat: 비밀번호 찾기 페이지 API 연동 (#223) - 완성
  src/components/common/Input.tsx
  src/components/page/signup/VerificationInput.tsx
  src/pages/auth/find/FindPasswordPage.tsx
Labels: 📬 API

#225 [Feat] 투자자 마이페이지 - 나의 관심 전략 모달 & 토스트 구현
  src/components/page/mypage-investor/myfolder/FolderHeader.tsx
  src/components/page/mypage-investor/myfolder/FolderList.tsx
  src/components/page/mypage-investor/myfolder/FolderModal.tsx
  src/pages/mypage/investor/InvestorFollowFolderPage.tsx
  src/pages/mypage/investor/InvestorMyPage.tsx
Labels: ✨ Feature

#229 [Feat] 닉네임 중복 API 연결 (#38)
  src/components/page/signup/SignUpForm.tsx
  src/constants/auth.ts
  src/hooks/mutations/useVerifacationMutation.tsx
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/pages/auth/find/FindPasswordPage.tsx
  src/types/error.ts
Labels: 📬 API

#231 [feat] 토스트 컴포넌트 타입 추가 (타입지정)
  src/components/common/Toast.tsx
  src/pages/test-page/ToastTestPage.tsx
  src/stores/toastStore.ts
Labels: 🎨 Html&css, ✨ Feature

#238 [Feat] 전략상세 일간분석(조회, 등록), 통계 조회 API 반영
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/StrategyIndicator.tsx
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/table/InputTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/components/page/strategy-detail/tabmenu/StatisticsTable.tsx
  src/constants/strategyAnalysis.ts
  src/hooks/mutations/useDailyAnalysis.ts
  src/hooks/queries/useFetchDailyAnalysis.ts
  src/hooks/queries/useStatistics.ts
  src/pages/strategy/StrategyDetailPage.tsx
  src/types/strategyDetail.ts
  src/utils/statistics.ts
Labels: 📬 API

#236 [Feat] 회원가입 이메일인증 기능구현 및 api 연동 + 관리자 인증 성공 후 관리자 전략승인페이지로 이동 처리
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/common/Header.tsx
  src/components/navigation/GlobalNav.tsx
  src/components/page/signup/AdminSessionTimer.tsx
  src/components/page/signup/SignUpForm.tsx
  src/components/page/signup/VerificationInput.tsx
  src/hooks/mutations/useAdminVerifyMutation.ts
  src/hooks/mutations/useAuthMutation.ts
  src/hooks/mutations/useNicknameValidation.ts
  src/hooks/mutations/useSignupEmailVerification.ts
  src/hooks/mutations/useSignupVerification.ts
  src/hooks/mutations/useVerifacationMutation.tsx
  src/hooks/useAdminAuthStatus.ts
  src/pages/auth/admin/AdminVerifyPage.tsx
  src/stores/adminAuthStore.ts
  src/stores/signupStore.ts
  src/types/auth.ts
  vite.config.ts
Labels: 📬 API, ✨ Feature

#241 [Feat] 투자자 마이페이지 - 나의 문의 API 연동 및 기능 구현
  src/api/apiEndpoints.ts
  src/api/myInquiry.ts
  src/components/page/mypage-investor/inquires-detail/Answer.tsx
  src/components/page/mypage-investor/inquires-detail/Question.tsx
  src/components/page/mypage-investor/inquires-edit/InquiresInput.tsx
  src/components/page/mypage-investor/inquires-edit/StrategyInfo.tsx
  src/hooks/mutations/useMyInquiry.ts
  src/hooks/mutations/useSubmitInquiryUpdate.ts
  src/pages/mypage/investor/MyInquiresDetailPage.tsx
  src/pages/mypage/investor/MyInquiresEditPage.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/types/myinquires.ts
Labels: 📬 API, ✨ Feature

#245 [Feat] formdata 전송을 위한 apiClient 수정 (#244)
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/api/strategyDetail.ts
  src/types/strategyDetail.ts
Labels: 📬 API, ✨ Feature

#246 [Feat] 관리자 매매유형, 상품유형 업로드 API 적용
  src/api/apiEndpoints.ts
  src/api/stockType.ts
  src/api/tradingType.ts
  src/api/uploadFile.ts
  src/components/page/admin/FileInput.tsx
  src/components/page/admin/TypeTable.tsx
  src/hooks/mutations/useIconMutation.ts
  src/hooks/mutations/useStockType.ts
  src/hooks/mutations/useTradingType.ts
  src/hooks/queries/useFetchStockType.ts
  src/hooks/queries/useFetchTradingType.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
Labels: 📬 API

#247 [Feat] 세션타이머 만료 시, 관리자 로그아웃 버튼 클릭 시, 로그아웃 처리 api 연동 (#242)
  src/api/apiClient.ts
  src/api/apiEndpoints.ts
  src/api/auth.ts
  src/components/common/Header.tsx
  src/components/navigation/AdminNav.tsx
  src/components/page/signup/AdminSessionTimer.tsx
  src/hooks/mutations/useAuthMutation.ts
  src/hooks/mutations/useVerifacationMutation.tsx
  src/mocks/handlers/auth.handlers.ts
  src/stores/adminAuthStore.ts
  src/stores/authStore.ts
  src/types/auth.ts
Labels: 📬 API, ✨ Feature

#254 [design] 트레이더 마이페이지 전략 스타일링
  src/pages/mypage/trader/TraderMyPage.tsx
Labels: 🎨 Html&css

#250 [Fix] 유형관리 이슈 해결(이제 봐주세욥 흑흑..)
  src/api/tradingType.ts
  src/api/uploadFile.ts
  src/components/common/ContentModal.tsx
  src/components/page/admin/FileInput.tsx
  src/hooks/queries/useFetchStockType.ts
  src/hooks/queries/useFetchTradingType.ts
  src/pages/admin/stock-type/StockTypeListPage.tsx
  src/pages/admin/trading-type/TradingTypeListPage.tsx
  src/stores/contentModalStore.ts
Labels: 🐞 BugFix

#260 [feat] 전략상세페이지 데이터를 State로 문의등록페이지에 데이터 연결하기
  src/components/page/inquiry-create/InquiryCreateForm.tsx
  src/components/page/strategy-detail/StrategyHeader.tsx
  src/pages/strategy/InquiryPage.tsx
  src/pages/strategy/StrategyDetailPage.tsx
Labels: ✨ Feature

#261 [Feat] 전략상세 일간분석 수정, 삭제 API 반영(예외처리중, 머지X)
  src/api/strategyDetail.ts
  src/components/page/strategy-detail/table/AnalysisTable.tsx
  src/components/page/strategy-detail/tabmenu/DailyAnalysis.tsx
  src/hooks/mutations/useDailyAnalysis.ts
  src/pages/strategy/StrategyDetailPage.tsx
Labels: 📬 API

#262 [Feat] 투자자/트레이더 문의 리스트 조회 API 연동 및 UI 수정 (브랜치 삭제하지말아주세요)
  src/api/inquiries/common.ts
  src/api/inquiries/trader.ts
  src/components/common/Avatar.tsx
  src/components/navigation/TraderMyPageNav.tsx
  src/components/page/mypage-trader/TraderAnswer.tsx
  src/components/page/mypage-trader/TraderQuestion.tsx
  src/components/page/mypage/InquiryStatusLabel.tsx
  src/constants/roles.ts
  src/constants/routes.ts
  src/hooks/queries/useFetchInquiries.ts
  src/hooks/queries/useFetchInquiryDetail.ts
  src/layouts/TraderMyPageLayout.tsx
  src/pages/mypage/investor/MyInquiriesPage.tsx
  src/pages/mypage/trader/InquiriesManagementPage.tsx
  src/pages/mypage/trader/InquiryDetailPage.tsx
  src/route/Router.tsx
  src/types/inquiries.ts
  src/utils/errorHandler.ts
Labels: 📬 API, 🎨 Html&css, 🔨 Refactor, ✨ Feature
